// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: dummy.sql

package store

import (
	"context"
)

const getAuthor = `-- name: GetAuthor :one
SELECT 'Hello World'
`

func (q *Queries) GetAuthor(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getAuthor)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}
