// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package store

import (
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Session struct {
	ID      string
	UserID  string
	Data    pqtype.NullRawMessage
	Expires time.Time
}

type User struct {
	ID          string
	DisplayName string
	Name        string
	Credentials pqtype.NullRawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
